name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Python Project
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Upgrade virtualenv
        run: pip install --upgrade virtualenv
      - name: Build project
        run: |
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py check

  # Software Component Analysis
  sca-safety:
    name: SCA - Safety
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull Safety Docker image
        run: docker pull hysnsec/safety
      - name: Run Safety
        run: docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json --save-json sca-safety-output.json 
        continue-on-error: true                   # Aiming DevSecOps maturity model level 1-2
      - name: Upload Safety Results
        uses: actions/upload-artifact@v4
        with:
          name: sca-safety-output.json
          path: sca-safety-output.json
        if: always()
  
  sca-retire:
    name: SCA - RetireJS
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        run: |
          sudo curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          sudo apt-get install -y nodejs
      - name: Install RetireJS
        run: npm i -g retire@latest
      - name: Install Project's Node.js Dependencies
        run: npm i
      - name: Run RetireJS
        run: retire --severity high --outputformat json --outputpath sca-retirejs-output.json
        continue-on-error: true                # Aiming DevSecOps maturity model level 1-2
      - name: Upload RetireJS Results
        uses: actions/upload-artifact@v4
        with:
          name: sca-retirejs-output.json
          path: sca-retirejs-output.json
        if: always()

# Static Application Security Testing 
  sast-trufflehog:
    name: SAST - Trufflehog
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull Trufflehog Docker image
        run: docker pull hysnsec/trufflehog
      - name: Run Trufflehog
        run: docker run --rm -v $(pwd):/src hysnsec/trufflehog filesystem /src --json --fail --no-update | tee sast-trufflehog-output.json
        continue-on-error: true 
      - name: Upload Trufflehog Results
        uses: actions/upload-artifact@v4
        with:
          name: sast-trufflehog-output.json
          path: sast-trufflehog-output.json
        if: always()

  sast-bandit:
    name: SAST- Bandit
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull Bandit Docker image
        run: docker pull hysnsec/bandit
      - name: Run Bandit
        run: docker run --rm --user $(id -u):$(id -g) -v $(pwd):/src hysnsec/bandit -r /src -f json -o /src/sast-bandit-output.json
        continue-on-error: true
      - name: Upload Bandit Results
        uses: actions/upload-artifact@v4
        with:
          name: sast-bandit-output.json
          path: sast-bandit-output.json
        if: always()

  test:
    name: Test Python Project
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Upgrade virtualenv
        run: pip install --upgrade virtualenv
      - name: Test project
        run: |
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py test taskManager
  
  release:
    name: Package the Web App as a Docker Image
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # registry: ${{vars.REGISTRY_URL}}
          username: ${{vars.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:latest

  # build-docker-image:
  #   name: Build and push the Docker image
  #   steps:
  #     - name: 

  # deploy:
  #   name: Deploy the latest image and run the container
  #   steps:

  # TODO: Deploy to Azure App Services
  # TODO: Deploy to Azure VM Linux