name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    
jobs:
  build:
    name: Build Python Project
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Upgrade virtualenv
        run: pip install --upgrade virtualenv
      - name: Build project
        run: |
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py check

  # Software Component Analysis
  sca-safety:
    name: Software Component Analysis - Safety
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull Safety Docker image
        run: docker pull hysnsec/safety
      - name: Run Safety
        run: docker run --rm -v ${{ github.workspace }}:/src hysnsec/safety check -r requirements.txt --json --save-json sca-safety-output.json 
      - name: Upload Safety Results
        uses: actions/upload-artifact@v3
        with:
          name: sca-safety-output.json
          path: sca-safety-result.json
        if: always()

  test:
    name: Test Python Project
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Upgrade virtualenv
        run: pip install --upgrade virtualenv
      - name: Test project
        run: |
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py test taskManager

        
